//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EINVOICE_BLUESEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Alt { get; set; }
        public string Description { get; set; }
        public string Thumnail { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        public Nullable<long> Cate_Id { get; set; }
        public string FullContent { get; set; }
        public int Sort { get; set; }
        public string Tags { get; set; }
    }
}
