//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dichvuhoanhao.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DichvuhoanhaoDbContext : DbContext
    {
        public DichvuhoanhaoDbContext()
            : base("name=DichvuhoanhaoDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<ItemService> ItemServices { get; set; }
        public virtual DbSet<LinkHeader> LinkHeaders { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Skype> Skypes { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Usercm> Usercms { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Whyme> Whymes { get; set; }
        public virtual DbSet<Mailsystem> Mailsystems { get; set; }
    }
}
