//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHDTNEWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string ShortDescription { get; set; }
        public string Image { get; set; }
        public int CountView { get; set; }
        public string FullContent { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<long> CateId { get; set; }
        public string tags { get; set; }
    }
}
