//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHDTNEWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BHDTNEWSEntities : DbContext
    {
        public BHDTNEWSEntities()
            : base("name=BHDTNEWSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NewsCate> NewsCates { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<ServiceDemo> ServiceDemoes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
    }
}
