//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHDTNEWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public long Id { get; set; }
        public string Package1 { get; set; }
        public string Price { get; set; }
        public string Discount { get; set; }
        public string Dauso { get; set; }
        public string Cuphap { get; set; }
        public string Webwap { get; set; }
        public string Quantity { get; set; }
        public string Slug { get; set; }
        public string ShortName { get; set; }
    }
}
