//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHDTNEWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDemo
    {
        public long Id { get; set; }
        public string ComName { get; set; }
        public string ProdName { get; set; }
        public string Hotline { get; set; }
        public string ProdCode { get; set; }
        public string TimeWarranti { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
    }
}
